version: "3.7"
networks:
  shared-network:
    driver: bridge
services:
  authentication-api:
    build:
      context: .
      dockerfile: _build/dockers/authentication-api.dockerfile
    networks:
        - shared-network
    ports:
        - "8081:8080"
  authentication-db:
      build:
          context: .
          dockerfile: _build/dockers/authentication-db.dockerfile
      image: authentication-db
      pid: "host"
      hostname: "host"
      ipc: host
      networks:
        - shared-network
      env_file:
        - _build/env/db/authentication-db.env
      ports:
        - "5432:5432"
  usermanagement-api:
    build:
      context: .
      dockerfile: _build/dockers/usermanagement-api.dockerfile
    networks:
        - shared-network
    depends_on:
      - authentication-db
    ports:
        - "8082:8080"
  usermanagement-db:
      build:
          context: .
          dockerfile: _build/dockers/usermanagement-db.dockerfile
      image: usermanagement-db
      pid: "host"
      hostname: "host"
      ipc: host
      networks:
        - shared-network
      env_file:
        - _build/env/db/user-management-db.env
      ports:
        - "5433:5432"