server:
  port: 8080
  context: "/authentication-service"
jwt:
  signingkey: "secret-key"
  maxHour: 1
service:
  usermanagement: "http://192.168.0.8:8082/user-management-service"
database:
  host: localhost
  port: 5432
  dbname: postgres
  username: postgres
  password: password
  sslmode: disable